openapi: 3.0.0
info:
  title: Email Service API
  description: API for sending customer satisfaction survey emails.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Development Server
paths:
  /survey/send-email:
    post:
      summary: Send a satisfaction survey email
      description: Sends an email containing a survey link to the customer.
      operationId: sendSurveyEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - name
                - restaurant
              properties:
                email:
                  type: string
                  format: email
                  description: The recipient's email address. *Required*
                name:
                  type: string
                  description: The recipient's name. *Required*
                restaurant:
                  type: string
                  description: The name of the restaurant. *Required*
      responses:
        '200':
          description: Survey email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Survey email sent successfully"
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request format"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to send email"
